apiVersion: monitoring.grafana.com/v1alpha1
kind: MetricsInstance
metadata:
  name: grafana-agent
  namespace: grafana-agent
  labels:
    app.kubernetes.io/instance: grafana-agent
    app.kubernetes.io/name: grafana-agent-metrics
spec:
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  remoteWrite: # one remote write for each tenant
  - name: <tenant-name>
    url: http://<mimir-public-hostname>/api/v1/push
    writeRelabelConfigs:
    - sourceLabels:
      - namespace
      regex: <tenant-name>
      action: keep
    oauth2:
      clientId:
        secret:
          name: <name-of-secret-with-client-id-and-secret>
          key: <key-in-secret-with-client-id>
      clientSecret:
        name: <name-of-secret-with-client-id-and-secret>
        key: <key-in-secret-with-client-secret>
      tokenUrl: https://<trace-shield-hydra-hostname>/oauth2/token
